# Generated by Django 2.2.1 on 2019-05-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_propertysellers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertySellers',
        ),
    ]
