# Generated by Django 2.2.1 on 2019-05-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_delete_propertysellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offers',
            name='expiration',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(blank=True, default='static/images/users/little-robin-hood-boys-costume.jpg', null=True, upload_to='static/images/users/'),
        ),
    ]
