# Generated by Django 2.2.1 on 2019-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20190510_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
