# Generated by Django 2.2.1 on 2019-05-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_checkoutinfo_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutInfo',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
