# Generated by Django 2.2.1 on 2019-05-14 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutinfo',
            name='city',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.', 'invalid_name')]),
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphanumeric characters are allowed.', 'invalid name')]),
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='street_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Only alphanumeric characters are allowed.', 'invalid street name')]),
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='zipCode',
            field=models.CharField(max_length=155, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only alphanumeric characters are allowed.', 'invalid zip')]),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=155, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 -]+$', 'Only alphabetic characters are allowed.', 'invalid country')]),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='address',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Only alphanumeric characters are allowed.', 'invalid address')]),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphanumeric characters are allowed.', 'invalid name')]),
        ),
    ]
