# Generated by Django 2.2.1 on 2019-05-14 20:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20190514_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='cvc',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^.{3}[0-9]*$', 'CVC must be 3 characters long and must only contain numbers')], verbose_name='CVC:'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^.{16}[0-9]*$', 'Credit card number must be 16 characters long and must only contain numbers')], verbose_name='Credit Card Number:'),
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='social',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^.{10}[0-9]*$', 'Social security number must be 10 digits long and must only contain numbers')], verbose_name='Social Security Number:'),
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='zipCode',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Zip must only contain numbers')], verbose_name='Zip:'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(blank=True, default='static/images/users/little-robin-hood-boys-costume.jpg', null=True, upload_to='static/images/users/', verbose_name='Profile image:'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='zipCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Properties.Zip', verbose_name='Zip:'),
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
