# Generated by Django 2.2.1 on 2019-05-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auto_20190514_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutinfo',
            name='feeling_lucky',
            field=models.BooleanField(default=False),
        ),
    ]
