# Generated by Django 2.2.1 on 2019-05-16 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_auto_20190516_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='cvc',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'CVC must be 3 characters long and must only contain numbers')], verbose_name='CVC:'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Credit card number must be 16 characters long and must only contain numbers')], verbose_name='Credit Card Number:'),
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='mobile',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Mobile must be 7 digits long and must only contain numbers')]),
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='social',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Social security number must be 10 digits long and must only contain numbers')], verbose_name='Social Security Number:'),
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='zipCode',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Zip must only contain numbers')], verbose_name='Zip:'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='social',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Social security number must be 10 digits long and must only contain numbers')]),
        ),
    ]
