# Generated by Django 2.2.1 on 2019-05-16 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_auto_20190516_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='social',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Social security number must be 10 digits long and must only contain numbers')], verbose_name='Social Security Number:'),
        ),
    ]
