# Generated by Django 2.2.1 on 2019-05-07 12:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.', 'invalid_category')])),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.', 'invalid_address')])),
                ('size', models.IntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('year_built', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.', 'invalid_year')])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.', 'invalid_zip')])),
                ('city', models.CharField(max_length=189, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.', 'invalid_city')])),
            ],
        ),
        migrations.CreateModel(
            name='PropertyVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(blank=True)),
                ('counter', models.PositiveIntegerField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.Properties')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(blank=True, max_length=999)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.Properties')),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='zip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.Zip'),
        ),
        migrations.CreateModel(
            name='OpenHouses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True)),
                ('length', models.PositiveIntegerField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.Properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=999, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.', 'invalid_description')])),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.Properties')),
            ],
        ),
    ]
