# Generated by Django 2.2.1 on 2019-05-08 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='propertyimages',
            name='images',
        ),
        migrations.AddField(
            model_name='properties',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Properties.Categories'),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='image',
            field=models.FileField(default='settings.MEDIA_ROOT/images/properties/el_escorial.jpg', upload_to='images/properties/'),
        ),
    ]
