# Generated by Django 2.2.1 on 2019-05-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='category_id',
        ),
        migrations.AddField(
            model_name='properties',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Properties.Categories'),
        ),
    ]
