# Generated by Django 2.2.1 on 2019-05-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0002_auto_20190508_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.FileField(upload_to='images/properties/'),
        ),
    ]
