# Generated by Django 2.2.1 on 2019-05-13 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0002_propertysellers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyvisits',
            name='week_number',
        ),
        migrations.AddField(
            model_name='propertyvisits',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.CharField(blank=True, max_length=4000, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.', 'invalid_description')]),
        ),
    ]
