# Generated by Django 2.2.1 on 2019-05-14 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0005_auto_20190514_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-Z -]*$', 'Category must only contain alphabetic characters')]),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.CharField(blank=True, max_length=4000, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáðéíóúýþæöÁÐÉÍÓÚÝÞÆÖ -]*$', 'Invalid character in description')]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='address',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáðéíóúýþæöÁÐÉÍÓÚÝÞÆÖ ]*$', 'Invalid character in address')]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='year_built',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^{4}[0-9]*$', 'Year must be 4 digits long and must only contain numbers')]),
        ),
        migrations.AlterField(
            model_name='zip',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z -]*$', 'City must only contain alphabetic characters')]),
        ),
        migrations.AlterField(
            model_name='zip',
            name='zip',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Zip must only contain numbers')]),
        ),
    ]
