# Generated by Django 2.2.1 on 2019-05-14 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0006_auto_20190514_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z -]*$', 'Category must only contain alphabetic characters')]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='address',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Záðéíóúýþæö ]*$', 'Invalid character in address')]),
        ),
        migrations.AlterField(
            model_name='zip',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z -]*$', 'City must only contain alphabetic characters')]),
        ),
        migrations.AlterField(
            model_name='zip',
            name='zip',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Zip must only contain numbers')]),
        ),
    ]
