# Generated by Django 2.2.1 on 2019-05-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0007_auto_20190514_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zip',
            options={'ordering': ['zip']},
        ),
    ]
