# Generated by Django 2.2.1 on 2019-05-16 17:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Properties', '0008_auto_20190515_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHouses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True)),
                ('length', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='properties',
            name='address',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáðéíóúýþæöÁÐÉÍÓÚÝÞÆÖ -]*$', 'Invalid character in address')]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='year_built',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', 'Year must be 4 digits long and must only contain numbers')]),
        ),
        migrations.AlterField(
            model_name='zip',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáðéíóúýþæöÁÐÉÍÓÚÝÞÆÖ -]*$', 'Invalid character in address')]),
        ),
        migrations.AddField(
            model_name='openhouses',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.Properties'),
        ),
        migrations.AddField(
            model_name='openhouses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
