# Generated by Django 2.2.1 on 2019-05-15 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0008_auto_20190515_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='address',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáðéíóúýþæöÁÐÉÍÓÚÝÞÆÖ -]*$', 'Invalid character in address')]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='year_built',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', 'Year must be 4 digits long and must only contain numbers')]),
        ),
        migrations.AlterField(
            model_name='zip',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáðéíóúýþæöÁÐÉÍÓÚÝÞÆÖ -]*$', 'Invalid character in address')]),
        ),
    ]
