# Generated by Django 2.2.1 on 2019-05-16 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0009_auto_20190516_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='year_built',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Year must be 4 digits long and must only contain numbers')]),
        ),
        migrations.DeleteModel(
            name='open_houses',
        ),
    ]
