# Generated by Django 2.2.1 on 2019-05-16 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0010_auto_20190516_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
